### ISSUE TITLE
Getting '[ERROR] list index out of range' when trying to load file

### ISSUE THREAD

**Issue by sunny-lan** [sashs/Ropper#43] opened 2016-07-30 15:28 UTC
Running Ropper on Windows, with capstone-windows 3.0.4, then entering the command `file C:\Users\MyUser\test.exe` results in the output:

```
[INFO] Load gadgets from cache
[LOAD] loading... 0%[ERROR] list index out of range
```

Then entering the command `search "% ?di"` results in the output:
[INFO] Searching for gadgets: "% ?di"
[ERROR] object of type 'NoneType' has no len()
[ERROR] Please report this error on https://github.com/sashs/ropper

Additionally, running the command `ropper.py --file C:\Users\MyUser\test.exe --
search "% ?di"` results in a continuous loop of this error:
[INFO] Load gadgets from cache
[LOAD] loading... 0%[ERROR] list index out of range
[ERROR] Please report this error on https://github.com/sashs/ropper

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\MyUser\Python\lib\multiprocessing\forking.py", line 347, in main
    self = load(from_parent)
  File "C:\Users\MyUser\Python\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Users\MyUser\Python\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Users\MyUser\Python\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by sashs** [comment] 2016-07-30 15:33
Hi,

could you provide the test.exe?


Best
Sascha

**Comment by sunny-lan-coder** [comment] 2016-07-31 19:55
Alright, here it is:
https://drive.google.com/file/d/0B7AnNw--HBtWM3VMZ3RyU09xWmc/view?usp=sharing
Do you need the source code?

**Comment by sashs** [comment] 2016-07-31 19:57
Thanks. No, I don't. The binary is enough. :)

**Comment by sunny-lan-coder** [comment] 2016-07-31 20:12
And I forgot to mention I am using Python 2.7.1...

**Comment by sashs** [comment] 2016-08-01 10:44
I need more information, because I cannot reproduce that. It works perfectly for me. I tested it with python2.7.1 and the current version. 

Which windows version?

What is the output of this command `print(__import__("sys").platform)`?

**Comment by sunny-lan-coder** [comment] 2016-08-09 15:23
My windows version is Windows 7, and the output of the command is `print(__import__("sys").platform)`

**Comment by sashs** [comment] 2016-08-09 16:10
Mh, strange. 
I tested it on a freshly installed Windows. It works for me. 
Which version of ropper did you use?

**Comment by sunny-lan-coder** [comment] 2016-08-09 17:23
I am using version 1.10.7...
Perhaps there is something wrong with my python installation

**Comment by sashs** [comment] 2016-08-20 21:29
Have you tried it again with a new python installation?

**Comment by QuarkTheAwesome** [comment] 2016-08-21 23:41
I'm getting this error too - tried reinstalling Python several times.

I'm trying to use an ELF for PowerPC (32 bit, big endian) using the latest master (320c242) on WSL (aka Bash on Ubuntu on Windows). Running Python 2.7.6, linux2. Fresh installs of capstone and filebytes, got 'em this morning. Any ideas? The executable is _technically_ copyrighted but I'll look around for another file that causes a similar issue.

**Comment by sashs** [comment] 2016-08-22 04:44
Hi,

the current problem is that I cannot reproduce this issue. Can you provide the file? If not, I will try to create an ELF file without section headers.

**Comment by user1029** [comment] 2017-07-27 12:25
I had the same problem. In my case I resolved it after deleting files from C:\Users\user\Local Settings\Temp\ropper_cache.

**Comment by bnbdr** [comment] 2018-05-29 21:36
Regarding the `list index out of range` error: 

The path for the cache on Windows is: `%USERPROFILE%\.ropper\cache`- clearing it helped.

@sashs, I think the issue with the `IndexError` (raised [here](https://github.com/sashs/Ropper/blob/master/ropper/service.py#L432)) is happening because there aren't necessarily `count` processes in the list.

**Comment by sashs** [comment] 2018-10-02 07:33
There are different changes in ropper, also in the cache. You can find it in the dev branch. Could someone retest this issue, please? I would like to close this issue.

**Comment by eternaleclipse** [comment] 2018-10-04 01:28
Tested on:
- Windows 10 standard cmd with Python 2.7.13
- WSL with Python 2.7.13

Cannot reproduce.

**Comment by sashs** [comment] 2018-10-04 05:37
At least your bug should be fixed now.

**Comment by eternaleclipse** [comment] 2018-10-06 20:15
Yep 👍

**Closed** 2018-10-06 20:18 UTC
