### ISSUE TITLE
Z3 was successfully installed. ; [ERROR] z3 has to be installed in order to use semantic search

### ISSUE THREAD

**Issue by dmiller423** [sashs/Ropper#164] opened 2022-11-01 00:03 UTC
Z3 was successfully installed. ; [ERROR] z3 has to be installed in order to use semantic search

**Comment by sashs** [comment] 2022-11-01 00:24
Hi, 
Ropper only shows that message if z3 cannot be imported. 
Are the z3 python bindings installed?
Can you import z3 in the python console?

**Comment by dmiller423** [comment] 2022-11-01 03:14
``Z3 was successfully built.
Z3Py scripts can already be executed in the 'build/python' directory.
Z3Py scripts stored in arbitrary directories can be executed if the 'build/python' directory is added to the PYTHONPATH environment variable and the 'build' directory is added to the LD_LIBRARY_PATH environment variable.
Use the following command to install Z3 at prefix /usr.
    sudo make install
null@rygar:/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/z3/build$ sudo make install
Z3 was successfully installed.
``

``pip install z3
Defaulting to user installation because normal site-packages is not writeable
Collecting z3
  Downloading z3-0.2.0.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting boto
  Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 9.5 MB/s eta 0:00:00
Building wheels for collected packages: z3
  Building wheel for z3 (setup.py) ... done
  Created wheel for z3: filename=z3-0.2.0-py3-none-any.whl size=26637 sha256=cc753960a6296fc78bc671e4ceb10963a2fdf32ed6a5df3de49876304f561510
  Stored in directory: /home/null/.cache/pip/wheels/5a/b2/60/55b07a5084cad7ab411e395fb1440a2b1a19598bff535a3955
Successfully built z3
Installing collected packages: boto, z3
Successfully installed boto-2.49.0 z3-0.2.0
``

``null@rygar:/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper$ ./Ropper.py --file ../x86_kernel_4.03.bin.elf --semantic "r8 = rax"
[INFO] Load gadgets from cache
[LOAD] loading... 100%
[LOAD] removing double gadgets... 100%
[INFO] Searching for gadgets: r8 = rax
[ERROR] archinfo has to be installed in order to use semantic search
``
``
null@rygar:/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper$ python
Python 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import z3
>>> 
``

**Comment by dmiller423** [comment] 2022-11-01 03:17
looks like I had tried to install the module and it failed,  and then built and installed and did not reinstall python module again... thx

**Comment by dmiller423** [comment] 2022-11-01 03:23
``
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/semantic.py", line 66, in analyse
    irsb = pyvex.IRSB(bytes(gadget.bytes), gadget.address+thumb, gadget.arch.info, bytes_offset=thumb, num_bytes=len(gadget.bytes), opt_level=0)
NameError: name 'pyvex' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/console.py", line 62, in cmd
    func(self, text)
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/console.py", line 1079, in do_semantic
    self.__rs.analyseGadgets(self.currentFile)
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/service.py", line 612, in analyseGadgets
    g.info = analyser.analyse(g)
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/semantic.py", line 73, in analyse
    except pyvex.PyVEXError as e:
NameError: name 'pyvex' is not defined
``

**Comment by sashs** [comment] 2022-11-01 08:22
Did you install pyvex as pointed out in the README as necessary dependendy for semantic search?

**Comment by dmiller423** [comment] 2022-11-01 16:37
yes

**Comment by sashs** [comment] 2022-11-01 16:54
Could you please check if it is installed correctly?

The error message says 
NameError: name 'pyvex' is not defined

which should be only the case if it could not be imported.

**Comment by dmiller423** [comment] 2022-11-01 17:06
Python 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvex
>>>

**Comment by sashs** [comment] 2022-11-01 17:22
Still the same error?
Which command do you use to start ropper?

**Comment by dmiller423** [comment] 2022-11-01 17:41
something like 

`./Ropper.py --file ../x86_kernel_4.03.bin.elf --semantic "r13 = r14"`

It worked one time when i reinstalled the z3 python module,  and then i changed the registers and it just started throwing exceptions

**Comment by dmiller423** [comment] 2022-11-01 17:44
``
null@rygar:/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel$ python3 ropper/Ropper.py --file ./x86_kernel_4.03.bin.elf --semantic "r13 = r14"
[INFO] Load gadgets from cache
[LOAD] loading... 100%
[LOAD] removing double gadgets... 100%
[ERROR] Please report this error on https://github.com/sashs/ropper
[ERROR] Traceback (most recent call last):
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/semantic.py", line 66, in analyse
    irsb = pyvex.IRSB(bytes(gadget.bytes), gadget.address+thumb, gadget.arch.info, bytes_offset=thumb, num_bytes=len(gadget.bytes), opt_level=0)
NameError: name 'pyvex' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/console.py", line 62, in cmd
    func(self, text)
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/console.py", line 1079, in do_semantic
    self.__rs.analyseGadgets(self.currentFile)
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/service.py", line 612, in analyseGadgets
    g.info = analyser.analyse(g)
  File "/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel/ropper/ropper/semantic.py", line 73, in analyse
    except pyvex.PyVEXError as e:
NameError: name 'pyvex' is not defined
``
`null@rygar:/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel$ python3`
```
Python 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvex
>>> pyvex.IRSB()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: IRSB.__init__() missing 3 required positional arguments: 'data', 'mem_addr', and 'arch'
>>> 
```

**Comment by sashs** [comment] 2022-11-01 22:12
I still think that this is an issue of your environment, because of the name error which says that pyvex is not known. 

Could you please execute in your bash
`/usr/bin/env python`

and there try to import pyvex. 
Afterwards you could try to execute ropper with your python interpreter
`python Ropper.py`


I've just created a docker container, and installed everything (ropper, pyvex, z3) and it works fine.

**Comment by dmiller423** [comment] 2022-11-01 22:17
I can import pyvex fine when I do that,  but both the git version and the version imported via pip both give the same exception that pyvex is not defined.  /shrug

**Comment by sashs** [comment] 2022-11-01 22:20
Can you import
`import z3
import pyvex
import archinfo`

**Comment by dmiller423** [comment] 2022-11-01 22:24
```

null@rygar:/media/null/TEMP/_RE/FS_dumps/4.03_x86_kernel$ /usr/bin/env python
Python 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import z3
>>> import pyvex
>>> import archinfo
>>> 
```

**Comment by sashs** [comment] 2022-11-01 22:28
Still same behaviour if you use this `python Ropper.py`

**Comment by sashs** [comment] 2022-11-01 22:33
Which OS do you use?

**Comment by dmiller423** [comment] 2022-11-01 22:52
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
```

**Comment by sashs** [comment] 2022-11-01 22:57
Have you tried it with `python Ropper.py`?

Sorry for the inconvenience, but I need to find out what the issue is. 
I tried it in gentoo and in a docker container with ubuntu 22.04.1 and everything works fine.

I will try it tomorrow on ubuntu 22.10.

**Comment by dmiller423** [comment] 2022-11-01 23:10
https://github.com/sashs/Ropper/issues/164#issuecomment-1298887445
^ using same python for both, and using `python-is-python3`

**Comment by sashs** [comment] 2022-11-03 13:47
I tried it with a fresh docker container with ubuntu 22.10 installed
I installed
```
apt install python-is-python3 z3 python3-pip python3-z3
pip install pyvex
pip install ropper
```

Afterwards I tried
```
ropper -f /bin/ls --semantic "rax==rbx"
```
works without issues. 

I assume there is something wrong with your environment

**Comment by sashs** [comment] 2022-11-07 11:43
Any update?

**Comment by dmiller423** [comment] 2022-11-07 17:43
I don't have time to debug the problem further,  so I've just written it off as a non-functional feature.
I tested every possible scenario I can think of and I couldn't tell you why it somehow doesn't see a package that's clearly installed and can be imported and used without trouble.  There are no alternate environments except one made in pycharm and z3 / pyvex work in that venv as they do at global scope.  Git repo and the version installed via pip both do the _exact_ same thing / there is no difference that could be explained away by local conflict in one.  I simply don't have any answers for you,  but I'm sure the issue will come back up again at some point: they always do.

**Comment by sashs** [comment] 2022-11-10 10:17
Ok. Nevertheless, many thanks for your support. 
Since I cannot reproduce the issue, even on the same operating system and python version, I will close this issue.

**Closed by sashs** 2022-11-10 10:17 UTC

**Comment by friendlyJLee** [comment] 2023-11-20 10:45
@dmiller423, If you encounter such an error, it's possible that you installed the 'z3' package instead of 'z3-solver', as both packages exist in Python with similar names. To resolve this, check your installed packages using 'pip list'. If 'z3' is installed but not 'z3-solver', first uninstall 'z3' with 'pip uninstall z3', and then install 'z3-solver' using 'pip install z3-solver'.
